import os
import matplotlib.pyplot as plt

def save_plot(filename: str = None, folder= '/home/zahemen/projects/BCGX---Customer-Churn-Analysis/visuals', dpi=300):
    """
    Saves the current Matplotlib plot to a specified folder with a given filename or an autogenerated name.

    Parameters:
    filename (str): The name of the file to save the plot as. If None, an autogenerated name is used.
    folder (str): The folder where the plot will be saved. The folder is created if it doesn't exist.
    dpi (int): The resolution of the saved plot in dots per inch.
    
    Returns:
    None
    """
    # Create the folder if it doesn't exist
    os.makedirs(folder, exist_ok=True)
    
    if filename is not None:
        # Save the plot with the provided filename
        file_path = os.path.join(folder, filename)
        plt.savefig(file_path, dpi=dpi, bbox_inches='tight')
    else:
        # Count existing files in the folder to create a unique filename
        file_count = sum(1 for file in os.listdir(folder) if os.path.isfile(os.path.join(folder, file)))
        # Create a unique filename
        file_path = os.path.join(folder, f'output_{file_count + 1}.png') if file_count > 0 else os.path.join(folder, 'output.png')
        plt.savefig(file_path, dpi=dpi, bbox_inches='tight')
    
    print(f"Plot saved at: {file_path}")
    return

# Example usage:
# save_plot('my_plot.png')  # Will save as 'visuals/my_plot.png'
# save_plot()  # Will save as 'visuals/output.png' or 'visuals/output_1.png', etc.

